### ISSUE TITLE
`v4_2` is a misuse of Cargo features.

### ISSUE THREAD

**Issue by Lymia** [Bluefinger/wyrand-rs#10]
If two crates depend on `wyrand`, and one sets `v4_2` and the other doesn't, the semantics of Cargo features will cause both to use the v4.2 hash codes. This could be very bad for crates that depend on consistent hashing and were built for the `v4` hashes. It'd probably be better to either drop support for v4 or make it two separate modules.

**Comment by Bluefinger** [comment]
The v4.2/v4 versions affect not just the hasher, but the `wyrand` module as well. However, I was intending on moving to v4.2 on a major version to deprecate v4, so what I might do is just accelerate with that plan given v4.2 is meant to have *better* quality entropy output than v4 anyway.

**Comment by Bluefinger** [comment]
@Lymia Feel free to take a look at #13 , which should resolve the issues with the resolver by splitting the two implementations into separate modules (also some nice things to ensure one can't mistakenly use parts of one with the other).
